[package]
name = "sscce"
version = "0.1.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"

[dependencies]

[dependencies.iced]
git = "https://github.com/hecrj/iced.git"
rev = "faa12382d4"
features = ["image"]
